### ISSUE TITLE
Batch entry of time logs from text file

### ISSUE THREAD

**Issue by DaniruKun** [platogo/atoss-cli#12]
As requested by @abangratz , some users log their time in an external tool first, and later use `atoss-cli` to log the entries in Atoss itself.
However, in the current implementation an entirely new WebDriver session is started and created for each time log.
Make it possible to parse an input file of time pairs, and log all of the entries in it within a single session.

@abangratz maybe you have an example of a desired format that we should support?

**Comment by abangratz** [comment]
the one I would prefer:

```csv
date,start,end,code
<2022-09-05 Mo>,9:00,17:30,wh
<2022-09-06 Di>,9:15,17:45,wh
<2022-09-07 Mi>,9:00,14:30,wh
<2022-09-07 Mi>,14:30,17:30,sd
<2022-09-08 Do>,,,
<2022-09-09 Fr>,9:00,17:30,
```
